name: rephub
description: "A medical representative app, built with Flutter and Supabase by Prince Bottoman."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  brick_offline_first_with_supabase: ^1.1.1
  brick_sqlite: ^3.1.1+1
  cached_network_image: ^3.4.1
  dart_mappable: ^4.3.0
  either_dart: ^1.0.0

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  hydrated_bloc: ^9.1.5
  logger: ^2.5.0
  sqflite: ^2.4.1
  supabase_flutter: ^2.8.1
  super_cupertino_navigation_bar: ^2.1.2
  uuid: ^4.5.1
  wolt_modal_sheet: ^0.9.4

dev_dependencies:
  brick_offline_first_with_supabase_build: ^1.0.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.3.0

  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
